[package]
name = "parse_weapons"
version = "0.1.0"
authors = ["Victor Gavrish <victor.gavrish@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.3.1"
encoding_rs = "0.8.17"
csv = "1.0"
structopt = "0.2"
